# Generated by Django 5.2.4 on 2025-08-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_playlist_created_at_alter_playlist_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedSong',
        ),
    ]
